"""application drafts

Revision ID: 574d31bbc19d
Revises: b5ddb9a23459
Create Date: 2026-07-26 12:43:01.435037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574d31bbc19d'
down_revision: Union[str, Sequence[str], None] = 'b5ddb9a23459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready_for_review', 'approved_by_specialist', 'exported', name='draftstatus'), nullable=False),
    sa.Column('filled_fields_json', sa.JSON(), nullable=True),
    sa.Column('skipped_fields_json', sa.JSON(), nullable=True),
    sa.Column('checklist_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('template_sha256', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('mapping_version', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_drafts_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_drafts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_drafts_id'))
        batch_op.drop_index(batch_op.f('ix_application_drafts_application_id'))

    op.drop_table('application_drafts')
    # ### end Alembic commands ###
