"""risk assessment with citations

Revision ID: 72ad37152e83
Revises: c493a4265e41
Create Date: 2026-07-26 02:14:37.841951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ad37152e83'
down_revision: Union[str, Sequence[str], None] = 'c493a4265e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('analysis_kind', sa.Enum('absolute_grounds', 'relative_grounds', 'combined', name='analysiskind'), nullable=False),
    sa.Column('overall_risk', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('limitations_json', sa.JSON(), nullable=True),
    sa.Column('missing_data_json', sa.JSON(), nullable=True),
    sa.Column('is_inconclusive', sa.Boolean(), nullable=False),
    sa.Column('inconclusive_reason', sa.Text(), nullable=True),
    sa.Column('knowledge_base_version', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('search_mode', sa.Enum('real', 'demo', 'limited', 'not_performed', name='searchmode'), nullable=False),
    sa.Column('sources_used_json', sa.JSON(), nullable=True),
    sa.Column('verification_json', sa.JSON(), nullable=True),
    sa.Column('requires_specialist_review', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_id'), ['id'], unique=False)

    op.create_table('risk_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=False),
    sa.Column('legal_basis', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('case_facts_json', sa.JSON(), nullable=True),
    sa.Column('missing_data_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('citations_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_json', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_decision', sa.Enum('approve', 'reject', 'modify', name='reviewerdecision'), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_findings_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_findings_id'), ['id'], unique=False)

    op.create_table('analysis_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_chunk_id', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('anchor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('verified', 'partial', 'not_found', 'source_missing', 'too_short', name='citationstatus'), nullable=False),
    sa.Column('matched_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['risk_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_chunk_id'], ['knowledge_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_citations_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_citations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_citations_knowledge_chunk_id'), ['knowledge_chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_citations_knowledge_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_citations_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_citations_finding_id'))

    op.drop_table('analysis_citations')
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_findings_id'))
        batch_op.drop_index(batch_op.f('ix_risk_findings_assessment_id'))

    op.drop_table('risk_findings')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_application_id'))

    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
