"""classes considered

Revision ID: a27fc1754377
Revises: 72ad37152e83
Create Date: 2026-07-26 11:35:00.417778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27fc1754377'
down_revision: Union[str, Sequence[str], None] = '72ad37152e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes_considered_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('classes_confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_column('classes_confirmed')
        batch_op.drop_column('classes_considered_json')

    # ### end Alembic commands ###
