"""inbound events

Revision ID: b5ddb9a23459
Revises: a27fc1754377
Create Date: 2026-07-26 12:13:22.946171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ddb9a23459'
down_revision: Union[str, Sequence[str], None] = 'a27fc1754377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual_upload', 'crm', 'email', 'webhook', 'api', name='sourcechannel'), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('links_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('received', 'linked', 'case_created', 'rejected', 'duplicate', name='inboundstatus'), nullable=False),
    sa.Column('target_case_id', sa.Integer(), nullable=True),
    sa.Column('processing_note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_case_id'], ['trademark_application_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_events_external_event_id'), ['external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_inbound_events_target_case_id'), ['target_case_id'], unique=False)

    op.create_table('inbound_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['inbound_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_attachments_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_attachments_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_attachments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_attachments_event_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_attachments_document_id'))

    op.drop_table('inbound_attachments')
    with op.batch_alter_table('inbound_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_events_target_case_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_inbound_events_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_events_external_event_id'))

    op.drop_table('inbound_events')
    # ### end Alembic commands ###
