"""baseline: полная схема (27 таблиц)

Revision ID: c493a4265e41
Revises: 
Create Date: 2026-07-25 18:10:56.138823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c493a4265e41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'waiting_human_review', 'completed', 'failed', 'retrying', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_id'), ['id'], unique=False)

    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Enum('application', 'missing_info_letter', 'legal_memo', 'power_of_attorney', name='templatetype'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('field_mapping_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_id'), ['id'], unique=False)

    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('law', 'regulation', 'methodology', 'template', 'practice', name='knowledgesourcetype'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_id'), ['id'], unique=False)

    op.create_table('prompt_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.JSON(), nullable=True),
    sa.Column('output_schema_json', sa.JSON(), nullable=True),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('guardrails_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_definitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_definitions_prompt_id'), ['prompt_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'lawyer', 'manager', 'client', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('company', 'individual', 'sole_proprietor', name='clienttype'), nullable=False),
    sa.Column('full_name_or_company_name', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('ogrn_or_ogrnip', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_source_id'), ['source_id'], unique=False)

    op.create_table('client_representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('poa_reference', sa.String(length=255), nullable=True),
    sa.Column('personal_data_consent_reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_representatives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_representatives_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_representatives_id'), ['id'], unique=False)

    op.create_table('trademark_application_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('assigned_lawyer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'info_requested', 'info_received', 'classification_pending', 'classification_review', 'classification_approved', 'legal_review_pending', 'legal_review_in_progress', 'legal_review_done', 'conflict_search_pending', 'conflict_search_in_progress', 'conflict_search_done', 'memo_generation', 'memo_approved', 'document_generation', 'document_approved', 'submitted', 'closed', name='applicationstatus'), nullable=False),
    sa.Column('mark_type', sa.Enum('word', 'figurative', 'combined', 'three_d', 'sound', 'color', 'other', name='marktype'), nullable=True),
    sa.Column('mark_name', sa.String(length=255), nullable=True),
    sa.Column('mark_text', sa.Text(), nullable=True),
    sa.Column('mark_image_file_id', sa.String(length=255), nullable=True),
    sa.Column('colors_claimed', sa.Text(), nullable=True),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('description_of_mark', sa.Text(), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('goods_services_raw', sa.Text(), nullable=True),
    sa.Column('territory', sa.String(length=255), nullable=True),
    sa.Column('priority_claim', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_lawyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trademark_application_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trademark_application_drafts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trademark_application_drafts_id'), ['id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('started', 'running', 'completed', 'failed', name='agentrunstatus'), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('conflict_search_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='searchjobstatus'), nullable=False),
    sa.Column('search_strategy_json', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_search_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_search_jobs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_search_jobs_id'), ['id'], unique=False)

    op.create_table('document_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('generation_status', sa.Enum('pending', 'generating', 'generated', 'failed', name='generationstatus'), nullable=False),
    sa.Column('completeness_check_result_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_packages_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_packages_id'), ['id'], unique=False)

    op.create_table('goods_services_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('proposed_class', sa.Integer(), nullable=False),
    sa.Column('approved_class', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('ai', 'manual', 'imported', name='itemsource'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_services_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_services_items_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_services_items_id'), ['id'], unique=False)

    op.create_table('legal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.Enum('absolute', 'relative', 'combined', name='reviewtype'), nullable=False),
    sa.Column('absolute_grounds_summary', sa.Text(), nullable=True),
    sa.Column('relative_grounds_summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('citations_json', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_decision', sa.Enum('approve', 'reject', 'modify', name='reviewerdecision'), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_reviews_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_reviews_id'), ['id'], unique=False)

    op.create_table('nice_class_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('class_description', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('primary', 'secondary', 'borderline', name='nicecategory'), nullable=True),
    sa.Column('risks_if_omitted', sa.Text(), nullable=True),
    sa.Column('risks_if_included', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nice_class_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nice_class_suggestions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nice_class_suggestions_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('info', 'warning', 'action_required', 'status_change', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Enum('proceed', 'modify', 'withdraw', 'further_review', name='recommendedaction'), nullable=True),
    sa.Column('recommended_classes_json', sa.JSON(), nullable=True),
    sa.Column('key_conflicts_json', sa.JSON(), nullable=True),
    sa.Column('key_risks_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_memos_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_memos_id'), ['id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('declared_content_type', sa.String(length=255), nullable=True),
    sa.Column('detected_mime', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('document_kind', sa.Enum('trademark_application', 'egrul_extract', 'egrip_extract', 'unknown_registry_extract', 'power_of_attorney', 'mark_image', 'other', 'unknown', name='documentkind'), nullable=False),
    sa.Column('kind_confidence', sa.Float(), nullable=True),
    sa.Column('kind_requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('uploaded', 'extracting', 'extracted', 'failed', 'rejected', name='documentprocessingstatus'), nullable=False),
    sa.Column('extraction_method', sa.Enum('pdf_text_layer', 'docx_parser', 'plain_text', 'regex', 'rule', 'ocr', 'llm_fallback', 'manual', name='extractionmethod'), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_channel', sa.Enum('manual_upload', 'crm', 'email', 'webhook', 'api', name='sourcechannel'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_sha256'), ['sha256'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('external_submission_id', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_status', sa.String(length=100), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_id'), ['id'], unique=False)

    op.create_table('conflict_search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_job_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('matched_mark', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=512), nullable=True),
    sa.Column('classes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('phonetic_score', sa.Float(), nullable=True),
    sa.Column('translit_score', sa.Float(), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('visual_score', sa.Float(), nullable=True),
    sa.Column('conflict_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_decision', sa.Enum('conflict', 'no_conflict', 'needs_review', name='conflictdecision'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_job_id'], ['conflict_search_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_search_results_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_search_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_search_results_search_job_id'), ['search_job_id'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.Enum('pdf_text_layer', 'docx_parser', 'plain_text', 'regex', 'rule', 'ocr', 'llm_fallback', 'manual', name='extractionmethod'), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_pages_id'), ['id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('pattern_id', sa.String(length=128), nullable=True),
    sa.Column('extraction_method', sa.Enum('pdf_text_layer', 'docx_parser', 'plain_text', 'regex', 'rule', 'ocr', 'llm_fallback', 'manual', name='extractionmethod'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('matched', 'missing', 'conflict', 'needs_review', 'confirmed', 'rejected', 'left_empty', name='fieldstatus'), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['trademark_application_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_path'), ['field_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_id'), ['id'], unique=False)

    op.create_table('legal_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_review_id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.Enum('absolute', 'relative', name='findingtype'), nullable=False),
    sa.Column('ground_article', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'blocking', name='findingseverity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['legal_review_id'], ['legal_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_findings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_findings_legal_review_id'), ['legal_review_id'], unique=False)

    op.create_table('submission_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=100), nullable=True),
    sa.Column('new_status', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_status_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_status_events_submission_id'), ['submission_id'], unique=False)

    op.create_table('field_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('pattern_id', sa.String(length=128), nullable=True),
    sa.Column('extraction_method', sa.Enum('pdf_text_layer', 'docx_parser', 'plain_text', 'regex', 'rule', 'ocr', 'llm_fallback', 'manual', name='extractionmethod'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_candidates_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_candidates_id'), ['id'], unique=False)

    op.create_table('field_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('accept', 'edit', 'reject', 'leave_empty', name='confirmationaction'), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('selected_candidate_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_candidate_id'], ['field_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_confirmations_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_confirmations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_confirmations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_confirmations_user_id'))
        batch_op.drop_index(batch_op.f('ix_field_confirmations_id'))
        batch_op.drop_index(batch_op.f('ix_field_confirmations_field_id'))

    op.drop_table('field_confirmations')
    with op.batch_alter_table('field_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_candidates_id'))
        batch_op.drop_index(batch_op.f('ix_field_candidates_field_id'))

    op.drop_table('field_candidates')
    with op.batch_alter_table('submission_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_status_events_submission_id'))
        batch_op.drop_index(batch_op.f('ix_submission_status_events_id'))

    op.drop_table('submission_status_events')
    with op.batch_alter_table('legal_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_findings_legal_review_id'))
        batch_op.drop_index(batch_op.f('ix_legal_findings_id'))

    op.drop_table('legal_findings')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_path'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_application_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_id'))
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('conflict_search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_search_results_search_job_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_search_results_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_search_results_application_id'))

    op.drop_table('conflict_search_results')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_application_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_source_documents_id'))
        batch_op.drop_index(batch_op.f('ix_source_documents_client_id'))
        batch_op.drop_index(batch_op.f('ix_source_documents_application_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('recommendation_memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_memos_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_memos_application_id'))

    op.drop_table('recommendation_memos')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('nice_class_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nice_class_suggestions_id'))
        batch_op.drop_index(batch_op.f('ix_nice_class_suggestions_application_id'))

    op.drop_table('nice_class_suggestions')
    with op.batch_alter_table('legal_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_legal_reviews_application_id'))

    op.drop_table('legal_reviews')
    with op.batch_alter_table('goods_services_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_services_items_id'))
        batch_op.drop_index(batch_op.f('ix_goods_services_items_application_id'))

    op.drop_table('goods_services_items')
    with op.batch_alter_table('document_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_packages_id'))
        batch_op.drop_index(batch_op.f('ix_document_packages_application_id'))

    op.drop_table('document_packages')
    with op.batch_alter_table('conflict_search_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_search_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_search_jobs_application_id'))

    op.drop_table('conflict_search_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_application_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('trademark_application_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trademark_application_drafts_id'))
        batch_op.drop_index(batch_op.f('ix_trademark_application_drafts_client_id'))

    op.drop_table('trademark_application_drafts')
    with op.batch_alter_table('client_representatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_representatives_id'))
        batch_op.drop_index(batch_op.f('ix_client_representatives_client_id'))

    op.drop_table('client_representatives')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('prompt_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_definitions_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_definitions_id'))

    op.drop_table('prompt_definitions')
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_id'))

    op.drop_table('knowledge_sources')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_id'))

    op.drop_table('document_templates')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_id'))

    op.drop_table('background_jobs')
    # ### end Alembic commands ###
